[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
eth-rpc-url = "${MAINNET_RPC_URL}"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}", url = "${GOERLI_RPC_URL}" }
mumbai = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "${MUMBAI_RPC_URL}" }
polygon_zk_testnet = { key = "${POLYGON_ZK_TESTNET_ETHERSCAN_API_KEY}", url = "${RPC_URL_POLYGON_ZKTEST}" }